### ISSUE TITLE
Help wanted: Testing and improvements for 4.0 milestone

### ISSUE THREAD

**Issue by danjagnow** [blizzard-net/warcraft#145]
The library is almost ready for the 4.0 milestone.  Now is the time to identify problems and make any final breaking changes.  Please test the [4.0.0-alpha.7](https://www.nuget.org/packages/ArgentPonyWarcraftClient/4.0.0-alpha.7) preview release and add comments here or create new issues for any problems you find.

- Do any of the methods produce errors for certain inputs (i.e., for JSON elements that are not always present)?
- Are there any missing APIs that need to be covered?
- Should any data types be changed (i.e., `long` to `int` in several places, or `long` to `DateTime` for timestamps)?
- Are any classes, properties, or interfaces badly named?  For example, does it make sense to have `ItemReference` and `ItemReferenceWithoutName` classes just because some APIs never return some properties?
- Are convenience methods needed for retrieving related information or media?

**Comment by willwolfram18** [comment]
One item I would recommend is possibly replacing `DateTime` with `DateTimeOffset`. While I know `DateTime` does have the `DateTimeKind` value in it, when working across multiple time zones, presenting the values with their offset is a little more helpful and explicit IMO.

**Comment by danjagnow** [comment]
> One item I would recommend is possibly replacing `DateTime` with `DateTimeOffset`.

This is complete with #147 now.

**Comment by danjagnow** [comment]
As far as I can tell, this release is ready to go.  I'm going to push out the 4.0 release, and we'll see what problems get reported.
