### ISSUE TITLE
Character Media API

### ISSUE THREAD

**Issue by TrisRA** [blizzard-net/warcraft#156]
Missing API - Character Media API
`/profile/wow/character/{realmSlug}/{characterName}/character-media`

`{
  "_links": {
    "self": {
      "href": "<URL>"
    }
  },
  "character": {
    "key": {
      "href": "<URL>"
    },
    "name": "<Name>",
    "id": <Id>,
    "realm": {
      "key": {
        "href": "<URL>"
      },
      "name": "<Name>",
      "id": <Id>,
      "slug": "<realm>"
    }
  },
  "avatar_url": "<URL>",
  "bust_url": "<URL>",
  "render_url": "<URL>"
}`

Cheers :)

**Comment by danjagnow** [comment]
This is available with the [4.1 release](https://www.nuget.org/packages/ArgentPonyWarcraftClient/4.1.0).
