### ISSUE TITLE
Tech Talent API

### ISSUE THREAD

**Issue by danjagnow** [blizzard-net/warcraft#161]
Add support for the Tech Talent API, which is a new addition to the [Game Data APIs](https://develop.battle.net/documentation/world-of-warcraft/game-data-apis) for the Shadowlands expansion.  See [WoW Shadowlands API Update - Covenants, Soulbinds, & More](https://us.forums.blizzard.com/en/blizzard/t/wow-shadowlands-api-update-covenants-soulbinds-more/13385) for details about the new APIs.

**Comment by willwolfram18** [comment]
I'm going to create a `TechTalentTreeReference` class as part of my work for #159  since the Soulbind portion of the covenant's API uses tech talent references.
