### ISSUE TITLE
CraftedItem in GetRecipeAsync is sometimes null

### ISSUE THREAD

**Issue by anteos59** [blizzard-net/warcraft#197]
In the response body for GetRecipeAsync there is not always a field "crafted_item". Sometimes (ex. recipeId 38729, Monel-Hardened Boots) this field doesn't exist, instead there are two fields "alliance_crafted_item" and "horde_crafted_item". 
It would be nice, if you could integrate these fields too.

**Comment by danjagnow** [comment]
I'll address this right after https://github.com/blizzard-net/warcraft/pull/198 is merged.

**Comment by anteos59** [comment]
Thanks a lot
