### ISSUE TITLE
WoW Classic API

### ISSUE THREAD

**Issue by anteos59** [blizzard-net/warcraft#204]
Am I missing something or is there no way to access the WoW Classic API?
Are there any plans to integrate it?

**Comment by danjagnow** [comment]
This request is a subset of https://github.com/blizzard-net/warcraft/issues/42.  I don't have any immediate plans to add support for the WoW Classic API, but it would probably be a separate **warcraft-classic** repository with code that is similar to this one, but it would publish a different set of NuGet packages with "Classic" in the name.  I haven't done any research to analyze the differences between the APIs to estimate the effort involved.  If there is sufficient demand, I would consider building it.  Or if someone would like to volunteer, I could bootstrap a repository with a small set of supported API endpoints to start from.

**Comment by anteos59** [comment]
I'm not quite sure if my experience is enough, but I'd like to try. If you would provide a repository for WoW Classic as a starting point, that would be really great.

**Comment by danjagnow** [comment]
I have created a repository at https://github.com/blizzard-net/warcraft-classic and done some initial work to match the APIs to what is supported for WoW Classic.  There will probably be many bug fixes that are required, but there is a starting point now.

**Comment by danjagnow** [comment]
See the [issues list](https://github.com/blizzard-net/warcraft-classic/issues) for the **warcraft-classic** repository for the steps that I believe need to be completed to get that project ready for a 1.0 release.
