### ISSUE TITLE
dragonflight update?

### ISSUE THREAD

**Issue by bonesoul** [blizzard-net/warcraft#205]
any work on dragonflight api compat?

**Comment by danjagnow** [comment]
I haven't done any work on this for a while.  Let me see how significant the API changes are...

**Comment by danjagnow** [comment]
@bonesoul, see https://github.com/blizzard-net/warcraft/pull/206 for some changes to get the tests working with the updated API.  If you can help identify any new APIs that need to be supported, I'll try to get them added and create a new release.

**Comment by danjagnow** [comment]
I've merged the changes to get the tests up and running again.  After reviewing the APIs, it looks like these are the gaps that need to be addressed before a release for Dragonflight, ignoring search-related APIs.  The Profile APIs appear to be complete currently.

## Achievement API

* Commodities

## Pet API

* Pet Media

## Talent API

* Talent Tree Index
* Talent Tree
* Talent Tree Nodes

**Comment by danjagnow** [comment]
The new release with support for Dragonflight is available: https://github.com/blizzard-net/warcraft/releases/tag/v8.0.24.
