### ISSUE TITLE
Add WoW Game Data

### ISSUE THREAD

**Issue by TravisBoatman** [blizzard-net/warcraft#52]

**Comment by TravisBoatman** [comment]
One of the problems I ran into while writing this new feature is how to handle the client secret. The WoW Game Data API requires an access token which is gained by sending your API Key and client secret to blizzard and they'll send you a token back. Which is then subsequently used for all API calls. There are 3 possible ways I've thought of to handle this client secret.

**Option 1 - Breaking Change**
Require both the API key and client secret when creating WarcraftClient.

**Option 2**
Make the client secret an optional parameter for a new WarcraftClient. However this can cause problems with using the library. If you try to use a method that accesses the WoW Game Data you'll get an error because you didn't supply the client secret key. This could be confusing to some users.

**Option 3**
Create another client for the WoW Game Data API along with the default WarcraftClient.

Thoughts?

**Comment by Bwolfing** [comment]
I'd personally say that's a separate client and interface. The WoW community APIs are a different set of services than the WoW Game Data APIs and therefore a different responsibility.

**Comment by danjagnow** [comment]
I agree that creating a separate client is a good idea.  There is a clear distinction between the kinds of data being retrieved by both APIs, and keeping the clients separated helps to avoid the complexity you noticed with initialization.

**Comment by danjagnow** [comment]
Now that there is no longer a Community API, I think this question is moot.  A single client should work.

**Comment by danjagnow** [comment]
I'm closing this issue.  Feel free to reopen if additional discussion is required.
