### ISSUE TITLE
Game Data API Usage

### ISSUE THREAD

**Issue by TravisBoatman** [blizzard-net/warcraft#56]
One of the big differences in the Game Data API json responses are the `links`.

For example...

```
{
    "_links": {
        "self": {
            "href": "https://us.api.battle.net/data/wow/connected-realm/11?namespace=dynamic-us"
        }
    },
    "id": 11,
    "has_queue": false,
    "status": {
        "type": "UP",
        "name": "Up"
    },
    "population": {
        "type": "FULL",
        "name": "Full"
    },
    "realms": [{
        "id": 11,
        "region": {
            "key": {
                "href": "https://us.api.battle.net/data/wow/region/1?namespace=dynamic-us"
            },
            "name": "North America",
            "id": 1
        },
        "connected_realm": {
            "href": "https://us.api.battle.net/data/wow/connected-realm/11?namespace=dynamic-us"
        },
        "name": "Tichondrius",
        "category": "United States",
        "locale": "enUS",
        "timezone": "America/Los_Angeles",
        "type": {
            "type": "PVP",
            "name": "PvP"
        },
        "is_tournament": false,
        "slug": "tichondrius"
    }],
    "mythic_leaderboards": {
        "href": "https://us.api.battle.net/data/wow/connected-realm/11/mythic-leaderboard/?namespace=dynamic-us"
    }
}
```

There are 4 `links` in this response. `self`, `region/key`, `connected_realm` and `mythic_leaderboards`.

These links are the API endpoints for whatever the json context may be. For example the `mythic_leaderboards` link will get the mythic leaderboards for the Tichondrius realm because Tichondrius is the realm that was requested.

These links can be useful in some scenarios. For example if I wasn't using an API wrapper. However I believe these links are not necessary to include in our API. Should we keep them or remove?

**Comment by danjagnow** [comment]
I have been keeping the links in the model classes, and I have been considering adding some extension methods to make it easy to retrieve related information when needed.

**Comment by danjagnow** [comment]
I'm closing this question as resolved; we'll keep the URLs represented in the model classes unless there is an objection.
