### ISSUE TITLE
New Developer Portal

### ISSUE THREAD

**Issue by TravisBoatman** [blizzard-net/warcraft#64]
Blizzard just announced their new developer portal. This includes but is not limited to new endpoints and responses. The full list can be found here: https://develop.battle.net/documentation/guides/migration-guide

**Comment by willwolfram18** [comment]
Happy to help with this once some specific differences are found (change in expected responses or addition of new endpoints).

**Comment by TravisBoatman** [comment]
Yeah that would be awesome! If you haven't already you should sign up for https://hacktoberfest.digitalocean.com/ to get a free t-shirt!

**Comment by willwolfram18** [comment]
That's the second reason I happened to stop by this repo; the Blizzard email was the first 😸

**Comment by TravisBoatman** [comment]
Do you have any features you want to work on?

**Comment by willwolfram18** [comment]
Well I've got good news and I've got bad news. The good news is, you're doing an excellent job maintaining this repo such that all the WoW Community API endpoints are all accounted for (which I know they were before), though I haven't investigated if any of the responses have changed. The bad news (which is technically still good news) is that I'm not sure there is anything for me to help contribute with! Where's a happy/sad smile when you need it?

Honestly that only things that come to mind are
* Removing the `InternalHttpClient` class altogether and requiring an `HttpClient` for all constructors
* Including extension methods in some kind of `ArgentPonyWarcraftClient.Extensions.DependencyInjection` (similar to how the `Microsoft.Extensions.DependencyInjection` is named) for wiring up the client easier.
    * I'd be interested in getting this to leverage the [`IHttpClientFactory`](https://docs.microsoft.com/en-us/dotnet/standard/microservices-architecture/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests). However, this would only allow the extensions library to target .NET Standard 2.0 which may not be desired.

**Comment by TravisBoatman** [comment]
That's funny, I've had those same ideas too! 

I remember I tried to create an extension method for the IServiceCollection for ASP.NET Core but ran into some problem. I can't remember what it was. I think we should revisit that though.

Also I've actually half implemented the WoW Community API's locally, I'll push it to origin as a new branch sometime soon.

**Comment by willwolfram18** [comment]
Well I'm certainly happy to take a swing at the `IServiceCollection` extensions! I've written one or two libraries for other projects which happen to do it 😺

**Comment by danjagnow** [comment]
The 3.0.0 release is intended to be compatible with the new developer portal, but I haven't put it through serious integration testing yet.  Please kick the tires so we can capture any issues and close this one out.

**Comment by danjagnow** [comment]
@willwolfram18, are you still interested in working on `IServiceCollection` extensions and adopting `IHttpClientFactory`?  The codebase is on .NET Standard 2.0 now.  Building a small utility library that makes it easy to enable dependency injection with `IServiceCollection` extensions sounds useful.

**Comment by willwolfram18** [comment]
You know what, that sounds like fun! I'll take a swing at it today!

**Comment by danjagnow** [comment]
Now that #143 has been merged, I believe this is ready to close.  Is there any other unfinished business here?

**Comment by willwolfram18** [comment]
From what I can tell that seems to be the case 😄 Not sure if we want to wait for @TravisBoatman to give the final thumbs up since he opened the original issue, but it seems like migration to the new APIs and DI capabilities have been added as the issue suggested.

**Comment by danjagnow** [comment]
I'm going to close this out.  Feel free to reopen if there are any remaining issues that should be addressed.
