### ISSUE TITLE
Add suport for mythics dungeons

### ISSUE THREAD

**Issue by Patresko** [blizzard-net/warcraft#69]
Is it possible to implement ?

[WoW Mythic Keystone Character Profile API](https://develop.battle.net/documentation/api-reference/world-of-warcraft-profile-api)

**Comment by TravisBoatman** [comment]
I'll look into this.

**Comment by Patresko** [comment]
Any update on this?

**Comment by danjagnow** [comment]
I believe this is now fully addressed in the [4.0.0-alpha.3](https://www.nuget.org/packages/ArgentPonyWarcraftClient/4.0.0-alpha.3) preview release.  See the [release notes](https://github.com/blizzard-net/warcraft/releases/tag/v4.0.0-alpha.3) for the new APIs added in this release.

**Comment by danjagnow** [comment]
I believe this is resolved, so I'm closing this issue.  Feel free to reopen if these APIs don't appear to be working or if there is trouble figuring out how to work with them.
