### ISSUE TITLE
GetCharactersAsync returns nothing

### ISSUE THREAD

**Issue by JohZant** [blizzard-net/warcraft#72]
There is a fair to good chance that I am just using this wrong, but I am getting no characters returned , or even an error returned, when using `GetCharactersAsync(string accessToken)`.

The `RequestResult` does have `Success` set to `false`, but the `Error` does not have it's properties populated and `Value` is `null`.

I stepped through the methods myself, and the `Get` method receives the correct URL with the users access token at the end, but then it gets its own token via `GetOAuthToken` and puts that token into the header.

When the `access_token` parameter and the Authorization header are different, I get an unauthorized response from Blizzard, but when I was stepping through the method and changed `_token` to be the same as the `access_token` parameter, I was able to retrieve all of the characters.

Is there somewhere else that I should be setting the `_token` object?

**Comment by danjagnow** [comment]
As of the [4.0 Preview 6 release](https://github.com/blizzard-net/warcraft/releases/tag/v4.0.0-alpha.6), this scenario is supported again.

```cs
string clientId = "MY-CLIENT-ID-GOES-HERE";
string clientSecret = "MY-CLIENT-SECRET-GOES-HERE";
var warcraftClient = new WarcraftClient(clientId, clientSecret);

// This is an OAuth access token for the user.
string accessToken = "ACCESS-TOKEN-GOES-HERE";

RequestResult<AccountProfileSummary> result = await warcraftClient.GetAccountProfileSummaryAsync(accessToken, "profile-us");
```

The access token is hard-coded in this sample, but real access tokens expire, so you'll need to acquire them dynamically.  You may want to look at [AspNet.Security.OAuth.BattleNet](https://www.nuget.org/packages/AspNet.Security.OAuth.BattleNet/) or a similar package to authenticate users and get access to a token for them.  For testing purposes, try using the [World of Warcraft Profile APIs](https://develop.battle.net/documentation/world-of-warcraft/profile-apis) and grabbing the access token from the end of the **Request URL** after submitting a request.
