### ISSUE TITLE
Use System.Text.Json

### ISSUE THREAD

**Issue by TravisBoatman** [blizzard-net/warcraft#79]
Migrating over to the new JSON library by Microsoft can have significant performance benefits compared to Newtonsoft.Json.

Scenario | Speed | Memory
-- | -- | --
Deserialization | 2x faster | Parity or lower
Serialization | 1.5x faster | Parity or lower
Document (read-only) | 3-5x faster | ~Allocation free for sizes < 1 MB
Reader | 2-3x faster | ~Allocation free (until you materialize values)
Writer | 1.3-1.6x faster | ~Allocation free

I have done some preliminary work. Migration has been straightforward however there are a few places where a custom converter is needed. Whereas Newtonsoft.Json had the feature built in.

Even though we have unit tests we should do some manual QA before releasing due to the major scope of this change.

Additionally, using this new JSON library requires netstandard2.0.

**Comment by danjagnow** [comment]
The library is targeting netstandard2.0 now, and all of the code for the old Community API is gone.  At this point, work should be mostly additive (plus refactoring as needed).  Would it make sense for me to pause changes for a while so there is a stable base for converting to **System.Text.Json**?
